### ISSUE TITLE
Add ptr check to getSpeed method in Player 

### ISSUE THREAD

**Issue by Rogal255** [coders-school/object-oriented-programming#100]
What happened when ship don't exist?

_Originally posted by @nauka-programowania-MA in https://github.com/coders-school/object-oriented-programming/pull/95#discussion_r661801843_

**Comment by ziobron** [comment]
🏅 2 XP granted for @Rogal255
Thanks for raising this Issue to help to make the course better!

**Comment by Rogal255** [comment]
Mistake, sorry.
