### ISSUE TITLE
Fixed overloading operator += and -= in (Cargo and Ship classes)

### ISSUE THREAD

**Issue by Martyna-Tu** [coders-school/object-oriented-programming#101]
What happened when we reach the limit of capacity or drop below 0? You need to handle error cases. Maybe throw exception, maybe return `std::nullopt` or `nullptr` maybe set some specific value like `std::numeric_limits::min/max`.

**Comment by ziobron** [comment]
🏅 2 XP granted for @Martyna-Tu
Thanks for raising this Issue to help to make the course better!

**Comment by Martyna-Tu** [comment]
sorry :]
