### ISSUE TITLE
Map.cpp random device should be a member of the class

### ISSUE THREAD

**Issue by gyrydymptum** [coders-school/object-oriented-programming#102]
I think this should be a member of the class. Creating a random device based on `mt19937` take time, and also can make some problems, because we have a limited resource of pseudo numbers.

_Originally posted by @nauka-programowania-MA in https://github.com/coders-school/object-oriented-programming/pull/95#discussion_r661798743_

**Comment by ziobron** [comment]
🏅 2 XP granted for @gyrydymptum
Thanks for raising this Issue to help to make the course better!

**Comment by gyrydymptum** [comment]
bad repository

**Comment by gyrydymptum** [comment]
bad repository
