### ISSUE TITLE
Issue in "Podstawy OOP | 0x14 override"

### ISSUE THREAD

**Issue by LechWilk** [coders-school/object-oriented-programming#108]
I guess we have wong calls here:
std::cout << birds_[0]->makeSound() << '\n';
std::cout << birds_[1]->makeSound() << '\n';
std::cout << birds_[2]->makeSound() << '\n';

Mothod makeSound() doesn't return any string to stream out in any override; instead of it already includes "std::cout":
class Goose : public Soundable {
public:
    void makeSound() override { std::cout << "Honk! Honk!"; }
};

class Hen : public Soundable {
public:
    void makeSound() override { std::cout << "Cluck! Cluck!"; }
};

class Duck : public Soundable {
public:
    void makeSound() override { std::cout << "Quack! Quack!"; }
};

**Comment by ziobron** [comment]
🏅 2 XP granted for @LechWilk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Nice catch, thanks! Already fixed.
